// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-vXydxF25T9oEuY9tDMDUNw6GzVkY99s',
    appId: '1:313973046644:web:028f1ecdcaad9e08f74021',
    messagingSenderId: '313973046644',
    projectId: 'app-catalogo-livro',
    authDomain: 'app-catalogo-livro.firebaseapp.com',
    storageBucket: 'app-catalogo-livro.firebasestorage.app',
    measurementId: 'G-VV565993VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXUA0NAJ-SOsU3vzoraqYWrnP1GjIiAB0',
    appId: '1:313973046644:android:2e3415abecdf9415f74021',
    messagingSenderId: '313973046644',
    projectId: 'app-catalogo-livro',
    storageBucket: 'app-catalogo-livro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ04bMU-9FECLlWptYCrluVFZsfrPiGc8',
    appId: '1:313973046644:ios:d0d63a8d5bc72963f74021',
    messagingSenderId: '313973046644',
    projectId: 'app-catalogo-livro',
    storageBucket: 'app-catalogo-livro.firebasestorage.app',
    iosBundleId: 'com.example.appCatalogo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ04bMU-9FECLlWptYCrluVFZsfrPiGc8',
    appId: '1:313973046644:ios:d0d63a8d5bc72963f74021',
    messagingSenderId: '313973046644',
    projectId: 'app-catalogo-livro',
    storageBucket: 'app-catalogo-livro.firebasestorage.app',
    iosBundleId: 'com.example.appCatalogo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-vXydxF25T9oEuY9tDMDUNw6GzVkY99s',
    appId: '1:313973046644:web:e59693af1e0b5af0f74021',
    messagingSenderId: '313973046644',
    projectId: 'app-catalogo-livro',
    authDomain: 'app-catalogo-livro.firebaseapp.com',
    storageBucket: 'app-catalogo-livro.firebasestorage.app',
    measurementId: 'G-HFR8JKTL1T',
  );
}
